# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dustforce Wiki
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-toc
  - jekyll-compress-images

imageoptim:
  svgo: false

df_techgroups:
  - basics
  - advanced
  - expert
  - mapmaking
  - other

df_mapgroups:
  - tutorials
  - forest
  - mansion
  - city
  - lab
  - difficults

df_enemygroups:
  - forest
  - mansion
  - city
  - lab
  - generic

collections:
  - playable_characters
  - maps
  - mechanics
  - enemies

defaults:
  -
    scope:
        path: "_mechanics"
    values:
        techgroup: "other"
  -
    scope:
        path: "_playable_characters"
    values:
        dash_speed: 0 # minimum dash speed
        hover_frames: 0 # frame count in hover state from jump (and raise, at least for worth)
        slope_slide_speed: 0 # max speed when pressing down on a slope
        fulljump_frames: 0 # frames before hover when jump is held when crouch_jump finishes
        shorthop_frames: 0 # frames before hover when jump is NOT held
        lightattack_frontswing_frames: 0 # frames before attack connects
        heavyattack_frontswing_frames: 0 # frames before attack connects
        lightattack_total_frames: 0 # frames before a new action can occur
        heavyattack_total_frames: 0 # frames before a new action can occur
        terminal_velocity: 0 # maximum falling speed
        terminal_velocity_frames: 0 # frames to reach maximum falling speed when falling off an edge
        terminal_velocity_downdash_frames: 0 # frames to reach max falling speed when downdash is pressed on the first possible frame (best case scenario)
        air_charges: 0 # maximum air charges

  -
    scope:
        path: "_enemies"
    values:
        game_name: null # TYPE_IDENTIFIER from dustmaker, e.g. enemy_stonebro, enemy_critter
        can_hurt: maybe # can inflict "damage" on the player in any way (e.g. prisms: false, spring blob: true)
        can_hurt_unprovoked: null # attacks without being provoked (assumes can_hurt=true) (e.g. wolf: true, butler: false)
        spawns_children: null # does enemy make sub enemies (chests, porcupines, trashcans, etc)
        spawns_children_child_id: null # if spawns_children is not null, this is the anchor name without the "enemy-" part (e.g. "prism-heavy")
        spawns_children_parent_id: null # ideally spawns_children_parent should have (spawns_children_id == this.name)
        reacts_to_attack: null # changes behavior (temporarily or permanently) if attacked, excluding hitstun (e.g. spring blob: true, tire: true, knight: false)
        can_path: null # can enemy be given a path, expects either can_path_grounded or can_path_flying if true
        can_path_grounded: null # can enemy attach to ground (gargoyle: false, porcupine: true)
        can_path_flying: null # can enemy fly on its own (stuck states do not count) (e.g. chests: false, butler: false, turkey: true)
        pacified_when_flying: null # if placed in air, is enemy frozen (assumes flying "no") (e.g. butler: true, chests: false)
        blocks: null # does enemy block attacks (e.g. knight: true, trashcan: false)
        massive: null # enemy can't be moved with attacks (e.g. large totem, golems)
        can_be_placed_from_editor: true # has entry in "entities" in the map editor
        hp: null # minimum number of damage to inflict before enemy dies

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _compress_images_cache.yml
  - _content-templates/
